# Generated by Django 5.0.4 on 2024-04-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managertournament', '0003_alter_team_options_team_score_alter_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='tournaments', to='managertournament.team'),
        ),
    ]
